{
  "info": {
    "name": "Copy Artist to Album Artist"
  }, 
  "Func0": {
    "fields": [
      "albumartist"
    ], 
    "arguments": [
      "%artist%"
    ], 
    "module": "puddlestuff.functions", 
    "func_name": "formatValue"
  }
}